### ISSUE TITLE
Additional clarifications needed for run-stats and stats endpoints

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#131]
The reasons for using run-stats and stats endpoints remain confusing. Clarify with additional description information within paths.

**Comment by johngriebel** [comment]
@jgwerner - looking at the code it seems the original intention was for the `stats` endpoint to present an aggregated view of a Server's all time statistics, while `run-stats` was intended to present information relevant to a specific run of the server, including some additional information such as `exit_code` and `stacktrace`. However, it seems the water has been muddied a bit, and they both provide essentially the same information. We should have a discussion to decide what we actually want the behavior to be.

**Comment by jgwerner** [comment]
@johngriebel agree.

**Comment by jkp85** [comment]
@johngriebel The idea behind `run-stats` was that we want to have a stats for single model request. [Here](https://github.com/3Blades/core-server/blob/master/run_http.go#L55) I'm creating `run-stats` object and function around it is like django view. It's called for every request. This was done like that, because we wanted user to see how many requests model get, how long every request took etc.
